### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by Masaru-0816** [Masaru-0816/freemarket_sample_68h#127]
■ URL
IPアドレス：http://52.2.174.0/
Github（最終課題のリポジトリ）：https://github.com/Masaru-0816/freemarket_sample_68h

■ Basic認証
ID：admin
Pass：1qazxsw2

■ テスト用アカウント
◯ 購入者用
メールアドレス：seller@seller.com
パスワード：11111111

◯ 購入用カード情報
番号：4242424242424242
期限：2月22日
セキュリティカード：123

◯ 出品者用
メールアドレス：aaa@gmail.com
パスワード： okok0722

**Comment by keisukekodama** [comment]
提出ありがとうございます！
確認させて頂いたところ、必須機能については問題ありませんでしたが、以下の不備が見受けられましたので修正をお願いします！

・出品している商品と値段
企業への提出物なので、以下の点を満たすよう実際のフリマアプリで出品されているような商品を出品しましょう。

```
出品数が少なすぎないか。最低でも3品目以上
出品内容・販売価格が適切か。服や靴、本などが無難です。
```


修正し次第、以下の完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfMuna4xX0zQ6_L8vRFrevse1I8VkCcdMp-24egzeH_JmIllg/viewform

**Comment by Masaru-0816** [comment]
上記修正致しました。
またテスト用アカウント名が間違えておりましたので、下記ご査収ください。

■ テスト用アカウント
◯ 購入者用
メールアドレス：buyer_user@gmail.com
パスワード：buyer_user

◯ 購入用カード情報
番号：4242424242424242
期限：2月22日
セキュリティカード：123

◯ 出品者用
メールアドレス：seller@seller.com
パスワード： 11111111

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by Masaru-0816** [comment]
ありがとうございます！
